version: '2'
services:
  mysql:
   image: mysql
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: root 
     MYSQL_DATABASE: test 
   ports:
     - 3308:3306
  adminer:
   image: adminer
   restart: always
   environment:
    ADMINER_DEFAULT_SERVER: mysql
   ports:
    - 8080:8080 
   links:
     - mysql   
